

proj5Base: proj5Base.o Point3d.o PointSet.o
	g++  -o proj5Base proj5Base.o Point3d.o PointSet.o

Point3d.o: Point3d.cpp
	g++ -g -c Point3d.cpp -o Point3d.o

PointSet.o: PointSet.cpp
	g++ -g -c PointSet.cpp -o PointSet.o 

proj5Base.o: proj5Base.cpp
	g++ -g -c proj5Base.cpp -o proj5Base.o 
